admin_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('admin_login/',views.admin_login,name='admin_login'),
    path('admin_logout/',views.admin_logout,name='admin_logout'),
    path('dashboard/', views.dashboard,name='admin_dasboard'),
    path('admin_product/', views.admin_product, name='admin_product'),
    path('admin_addProduct/',views.admin_addProduct,name='admin_addProduct'),
    
    path('admin_category',views.adminCategory,name='admin_category'),

    path('admin_messages',views.adminMessages,name='adminMessages'),
    path('delete_message/<int:id>',views.deleteMessage,name='deleteMessage'),
    path('reply_message',views.replyMessage,name='replyMessage'),
]

core/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('',views.home,name='home'),
    path('blog/',views.blog,name='blog'),
    path('checkout/',views.checkout,name='checkout'),
    path('confirmation/',views.confirmation,name='confirmation'),
    path('contact/',views.contact_us,name='contact_us'),
    path('elements/',views.elements,name='elements'),
    path('tracking/',views.tracking,name='tracking'),
    path('single_blog/',views.single_blog,name='single_blog'),
    path('cp_register/',views.cp_register,name='cp_register'),
    path('cp_login/',views.cp_login, name='cp_login'),
    
     path('activate/<uidb64>/<token>/', views.cp_activate, name='cp_activate'),
     path('cp_register/cp_login/', views.cp_login, name='cp_login_email'),
     
     path('api/',views.api_call,name='api')
    
    
]

shoppy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/',include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('shoppyadmin/', admin.site.urls),
    path('admin/',include('admin_app.urls')),
    path('',include('core.urls')),
    path('category/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/',include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_app/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from category.models import Category 
from django.urls import reverse
from django.utils.html import mark_safe


from accounts.models import Account


# Create your models here.
class Product(models.Model):
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=500,blank=True)
    price           = models.FloatField()
    images          = models.ImageField(upload_to='photos/prodcuts')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)
    is_featured     = models.BooleanField(default=False)
    
    
    def get_url(self):
        return reverse('product_details', args=[self.category.slug, self.slug])
    
    def __str__(self):
        return self.product_name
    
    def is_stock_zero(self):
        if self.stock == 0:
            return mark_safe('<a href="{}">{} - out of stock</a>'.format(self.get_url(), self.product_name))
        return ''
    


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)

variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value     = models.CharField(max_length=100)
    is_active           = models.BooleanField(default=True)
    created_date        = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value
    
    

    
    
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.subject
    
    

class Banner(models.Model):
    banner_name    = models.CharField(max_length=200, unique=True)
    b_description     = models.TextField(max_length=500,blank=True)
    price           = models.FloatField()
    b_images          = models.ImageField(upload_to='photos/banners')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    
  
    def __str__(self):
        return self.banner_name
    
    def get_related_products(self):
        if self.is_available:
            related_products = Product.objects.filter(
                product_name__startswith=self.banner_name
            )
            return related_products
        return None
    
    
class ProductGallery(models.Model):
    
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)
    
    def __str__(self):
        return self.product.product_name
    
    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'
        
        

admin_app/forms.py
from django import forms
from store.models import Product

class productForm(forms.ModelForm):
    class Meta:
         model = Product
         fields = ['product_name', 'slug', 'description', 'price', 'images', 'stock',
                      'is_available', 'is_featured', 'category', ]
        
    def __init__(self, *args, **kwargs):
        super(productForm,self).__init__(*args, **kwargs)
        self.fields['price'].widget.attrs['min'] = 0
        self.fields['stock'].widget.attrs['min'] = 0
        for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['is_available'].widget.attrs['type'] = 'checkbox'
        self.fields['is_featured'].widget.attrs['type'] = 'checkbox'
        self.fields['is_available'].widget.attrs['class'] = 'form-check-input'
        self.fields['is_featured'].widget.attrs['class'] = 'form-check-input'

admin_app/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from store.models import *
from category.models import *
from orders.models import *
from django.http import HttpResponse
import calendar
from datetime import datetime,timedelta
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from django.contrib.auth import authenticate, login
from django.contrib import messages, auth
from django.core.paginator import Paginator
from .forms import productForm

from core.models import ContactUs
from django.core.mail import EmailMessage


from django.db.models import Sum



def admin_login(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = auth.authenticate(request, username=username, password=password)
        

        if user is not None and user.is_active and user.is_superadmin:
            login(request, user)
            
            return redirect('admin_dasboard')
        
        else:
            return render(request, 'admin_login.html', {'error_message' : 'Invalid Credentials'})
        
    else:
        return render(request, 'admin_login.html')
    
    
def admin_logout(request):
    auth.logout(request)
    messages.success(request, 'Your are Logged out')
    return redirect('admin_login')



def dashboard(request):
    total_users = Account.objects.count()
    total_product = Product.objects.count()
    total_categorey = Category.objects.count()
    total_orders = OrderProduct.objects.count()
    total_coupon = Coupon.objects.count()
    total_sales = OrderProduct.objects.filter(ordered=True).aggregate(Sum('product_price'))['product_price__sum']
    
    today = datetime.today()
    this_year = today.year
    this_month = today.month
    
    # Define first_order_date
    # first_order_date = Order.objects.earliest('created_at').created_at
    
    # label_list = []
    # line_data_list = []
    # bar_data_list =  []
    # month_list=[]
    # for year in range(first_order_date.year,this_year+1) :
    #     month = this_month if year==this_year else 12
    #     month_list= month_list+(list(map(lambda x : calendar.month_abbr[x]+'-'+str(year),range(1,month+1))))[::-1]
    # for year in range(2022,(this_year+1)):
    #     this_month = this_month if year==this_year else 12
    #     for month in range(1,(this_month+1)):
    #         month_wise_total_orders = Order.objects.filter(is_ordered=True,created_at__year = year,created_at__month=month,).order_by('created_at').count()
    #         month_name = calendar.month_abbr[month]
    #         label_update = str(month_name)+ ' ' + str(year)
    #         label_list.append(label_update)
    #         line_data_list.append(month_wise_total_orders)
    # for year in range(2022,(this_year+1)):
    #     for month in range(1,(this_month+1)):
    #         monthwise_orders = Order.objects.filter(is_ordered=True,created_at__year = year,created_at__month=month,)
    #         monthwise_sales  = round(sum(list(map(lambda x : x.order_total,monthwise_orders))),2)
    #         bar_data_list.append(monthwise_sales)
    context = {
        'total_users' :total_users,
        'total_product' : total_product,
        'total_categorey' : total_categorey,
        'total_orders' : total_orders,
        'total_coupon' : total_coupon,
        'total_sales' : total_sales,
        # 'month_list'      : month_list,
        # 'line_labels'     : label_list,
        # 'line_data'       : line_data_list,
        # 'bar_data'        : bar_data_list
    }
    return render(request,'admindashboard.html', context)


# @login_required(login_url='admin_login')
def admin_product(request):
    products = Product.objects.all().filter(is_available=True)
    category = Category.objects.all()

    context = {
        'products' : products,
        'category' : category
    }
    
    return render(request,'admin_product.html',context)


def admin_addProduct(request):
    if request.method == 'POST':
        # Extract form data from the POST request
        product_name = request.POST.get('product_name')
        slug = request.POST.get('slug')
        description = request.POST.get('description')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        is_available = request.POST.get('is_available')
        is_featured = request.POST.get('is_featured')
        category_id = request.POST.get('category')  # Assuming category is sent as ID
        
        # Handle image upload
        image = request.FILES.get('images')  # Assuming the input name is 'images'
        
        # Save the form data into the Product model
        product = Product(
            product_name=product_name,
            slug=slug,
            description=description,
            price=price,
            stock=stock,
            is_available=bool(is_available),
            is_featured=bool(is_featured),
            category_id=category_id,  # Assuming category is sent as ID
            images=image  # Save the image
        )
        product.save()

        return HttpResponse('Product successfully added!')  # Modify this as needed

    # Fetch categories to populate the dropdown in the form
    categories = Category.objects.all()
    
    return render(request, 'admin_addProduct.html', {'categories': categories})


def adminCategory(request):
    brand = Category.objects.all()
    context = {
        brand : "brand"
    }

    return render(request,'admin_category.html',context)




# @login_required(login_url = 'admin_login')
def adminMessages(request):
    messages_recieved  = ContactUs.objects.all().order_by('-sent_time')
    context = {
        'messages_recieved' : messages_recieved,
    }
    return render(request,'admin_messages.html',context)


# @login_required(login_url = 'admin_login')
def deleteMessage(request,id):
    message = ContactMessage.objects.get(id=id)
    message.delete()
    messages.error(request,'message deleted successfully!')
    return redirect('adminMessages')


# @login_required(login_url = 'admin_login')
def replyMessage(request):
    try:
        if request.method == 'POST':
            email = request.POST['email']
            message = request.POST['message']
            mail_subject = ''' Reply from Fresh Harvest Ecommerce shop'''
            send_mail = ContactUs(mail_subject,message,to=[email])
            send_mail.send()
            messages.success(request,'Message sent successfully')
            return redirect('adminMessages')
        else:
            messages.error(request,'please fill the form correctly')
        
    except:
        messages.error(request,'Server down! please ensure you are connected to internet')
        return redirect('adminMessages')
        

admin_app/templates/admin_addProduct.html
{% extends 'admin_base.html' %}
{% load static %}



{% block content %}
<div class="main-panel">
    <div class="content-wrapper" >
      <div class="">
        <div class="page-header ">
          <h2 class="page-title " style="margin-left: 4rem;">Add Product</h2>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active" aria-current="page"></li>
            </ol>
          </nav>
        </div>
        {% include 'alert.html' %}
        <form action="{% url 'admin_addProduct' %}" method="post" enctype="multipart/form-data" class="mt-4">
          {% csrf_token %}
          <div class="form-group">
              <label for="product_name">Product Name</label>
              <input type="text" class="form-control" id="product_name" name="product_name" required>
          </div>
          <div class="form-group">
              <label for="slug">Slug</label>
              <input type="text" class="form-control" id="slug" name="slug" required>
          </div>
          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" id="category" name="category" required>
                <option value="">Select a category</option>
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.category_name }}</option>
                {% endfor %}
            </select>
        </div>
        
          <div class="form-group">
              <label for="description">Description</label>
              <textarea class="form-control" id="description" name="description" rows="3"></textarea>
          </div>
          <div class="form-group">
              <label for="price">Price</label>
              <input type="number" class="form-control" id="price" name="price" step="0.01" required>
          </div>
          <div class="form-group">
              <label for="images">Images</label>
              <input type="file" class="form-control-file" id="images" name="images" accept="image/*" required>
          </div>
          <div class="form-group">
            <label for="images">Images</label>
            <input type="file" class="form-control-file" id="images" name="images" accept="image/*" required>
        </div>
        <div class="form-group">
            <label for="images">Images</label>
            <input type="file" class="form-control-file" id="images" name="images" accept="image/*" required>
        </div>
          <div class="form-group">
              <label for="stock">Stock</label>
              <input type="number" class="form-control" id="stock" name="stock" required>
          </div>
          <div class="form-check">
              <input type="checkbox" class="form-check-input" id="is_available" name="is_available" checked>
              <label class="form-check-label" for="is_available">Is Available</label>
          </div>
          <div class="form-check">
              <input type="checkbox" class="form-check-input" id="is_featured" name="is_featured">
              <label class="form-check-label" for="is_featured">Is Featured</label>
          </div>
          <div class="form-group mt-3">
              <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      </form>
          </div>

</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  const productNameInput = document.querySelector('#id_product_name');
  const slugInput = document.querySelector('#id_slug');

  productNameInput.addEventListener('input', function() {
    const product_name = this.value;
    const slug = product_name.replace(/\s+/g, '-').toLowerCase();
    slugInput.value = slug;
});
</script>
{% endblock content %}

admin_app/templates/admin_category.html
{% extends 'admin_base.html' %}
{% load static %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper" >
      <div class="">
        <div class="page-header ">
          <h2 class="page-title " style="margin-left: 4rem;">Brand</h2>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-ite"><a href="{% url 'admin_addProduct' %}" class="btn btn-success">+ Add Brand</a></li>
              <li class="breadcrumb-item active" aria-current="page"></li>
            </ol>
          </nav>
        </div>
        {% include 'alert.html' %}
        <div class="container">
            <form action="{% url 'admin_product' %}" id="searchForm" method="POST">
                {% csrf_token %}
                <div class="d-flex justify-content-center">
            <input class="form-control w-50  mb-5 d-inline-block" type="search" placeholder="Search" aria-label="Search" name="search" >
            <button class="mdi mdi-yeast mb-5 " style="border-radius: 0.3rem;" type="submit"></button>
                </div>
            </form>
            
            {% if not products %}
                 
            <h3> No products of this name!</h3>
            
            {% else %}
                 
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Brand Name</th>
                  
                  <th>Product Description</th>
                  <th>Total Products</th>
                  <th>Description</th>
                  <th>Stock</th>
                  <th>is_available</th>
                  <th>is_featured</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for brand in brand %}
                    <tr style="height: 50px !important;" class="text-wrap">
                        <td>{{ brand.category_name }}</td>
                        <td>{{ product.category. }}</td>
                        <td>{{ product.category.sub_category }}</td>
                        <td>₹{{ product.price }}</td>
                        <td style="max-height: 20px;">{{ product.description|truncatechars:20 }}</td>
                        <td>{{ product.stock }}</td>
                        <td>{% if product.is_available %}Available{% else %}Not Available{% endif %}</td>
                        <td>{% if product.is_featured %}Featured{% else %}Not Featured{% endif %}</td>
                        <td>
                            <div class="pro-img-overlay">
                                <a href=""><i class="mdi mdi-tooltip-edit"></i></a>
                            </div>
                        </td>
                        <td>
                            <div class="pro-img-overlay">
                                <a href="" data-toggle="modal" data-target="#modal{{ product.id }}">
                                    <i class="mdi mdi-delete-forever text-danger"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="modal{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Delete Product?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body text-left">
                                    Are you sure you want to delete <b>{{ product.product_name }}</b>?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                    <a href="" type="button" class="btn btn-primary">Yes</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </tbody>
            </table>
          
            <nav aria-label="Page navigation example" class="mt-3">
              <ul class="pagination d-flex justify-content-center">
                {% if products.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="?page={{ products.number }}">{{ products.number }}</a></li>
                {% if products.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">{{ products.next_page_number }}</a></li>
                {%endif%}
            
                {% if products.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
                {%endif%}
              </ul>
            </nav>
            {% endif %}
          </div>
        
    </div>
</div>


{% endblock content %}

admin_app/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: sans-serif;
            background: #0a0606e5;
        }
        
        .card{
            margin-bottom:20px;
            border:none;
        }
        
        .box {
            width: 500px;
            padding: 40px;
            position: absolute;
            top: 50%;
            left: 50%;
            
            ;
            text-align: center;
            transition: 0.25s;
            margin-top: 100px
        }
        
        .box input[type="text"],
        .box input[type="password"] {
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #3498db;
            padding: 10px 10px;
            width: 250px;
            outline: none;
            color: white;
            border-radius: 24px;
            transition: 0.25s
        }
        
        .box h1 {
            color: white;
            text-transform: uppercase;
            font-weight: 500
        }
        
        .box input[type="text"]:focus,
        .box input[type="password"]:focus {
            width: 300px;
            border-color: #2ecc71
        }
        
        .box input[type="submit"] {
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #2ecc71;
            padding: 14px 40px;
            outline: none;
            color: white;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer
        }
        
        .box input[type="submit"]:hover {
            background: #2ecc71
        }
        
        .forgot {
            text-decoration: underline
        }
        
        ul.social-network {
            list-style: none;
            display: inline;
            margin-left: 0 !important;
            padding: 0
        }
        
        ul.social-network li {
            display: inline;
            margin: 0 5px
        }
        
        .social-network a.icoFacebook:hover {
            background-color: #3B5998
        }
        
        .social-network a.icoTwitter:hover {
            background-color: #33ccff
        }
        
        .social-network a.icoGoogle:hover {
            background-color: #BD3518
        }
        
        .social-network a.icoFacebook:hover i,
        .social-network a.icoTwitter:hover i,
        .social-network a.icoGoogle:hover i {
            color: #fff
        }
        
        a.socialIcon:hover,
        .socialHoverClass {
            color: #44BCDD
        }
        
        .social-circle li a {
            display: inline-block;
            position: relative;
            margin: 0 auto 0 auto;
            border-radius: 50%;
            text-align: center;
            width: 50px;
            height: 50px;
            font-size: 20px
        }
        
        .social-circle li i {
            margin: 0;
            line-height: 50px;
            text-align: center
        }
        
        .social-circle li a:hover i,
        .triggeredHover {
            transform: rotate(360deg);
            transition: all 0.2s
        }
        
        .social-circle i {
            color: #fff;
            transition: all 0.8s;
            transition: all 0.8s
        }
    </style>
</head>
<body>
    

    <div class="container mt-5"> 
        <div class="row">
            {% include 'alert.html' %}
            <div class="col-md-6"> 
                <div class="card mr-5"> 
                    <form  action="{% url 'admin_login' %}" method="POST" class="box"> 
                        {% csrf_token %}
                        <h1>Login</h1> <br><br><br> 
                         
                        <input type="text" name="username" id="email" placeholder="Username" required>
                         <input type="password" name="password" id="password" placeholder="Password" required> 
                         <a class="forgot text-muted" href="#">Forgot password?</a> 
                         <input type="submit" name="" value="Login" href="#"> 
                    </form>
                </div> 
            </div> 
        </div>
    </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <script>
    setTimeout(function(){
        $('#message').fadeOut('slow')
       },4000)
  </script>
</body>
</html>